#define davorengine_UP SDLK_UP
#define davorengine_DOWN SDLK_DOWN
#define davorengine_LEFT SDLK_LEFT
#define davorengine_RIGHT SDLK_RIGHT
#define davorengine_W SDLK_w
#define davorengine_S SDLK_s
#define davorengine_A SDLK_a
#define davorengine_D SDLK_d
#define davorengine_E SDLK_e
